### ISSUE TITLE
Investigate using smol in place of tokio

### ISSUE THREAD

**Issue by darinmorrison** [wasm-lsp/wasm-language-server#36]

**Comment by ebkalderon** [comment]
I believe it would require some restructuring in `tower-lsp`, unfortunately, since`Server` and the internal delegate types use `tokio::spawn()` in a few places. I can look into achieving this within the next few releases, if possible!

**Comment by darinmorrison** [comment]
@ebkalderon thanks for the note! I was wondering about this. Compatibility with `smol` would indeed be an interesting feature for the future. I may try to experiment with it some and possibly make a PR if you don't get to it first. But I should probably focus on getting a basic release of this done before worrying too much about the other async options 🙂

**Comment by ebkalderon** [comment]
Tying together https://github.com/ebkalderon/tower-lsp/issues/180 to this issue.

I've managed to eliminate one use of `tokio::spawn` and also fixed a critical bug in the client request routing by using `futures::join!()` instead ([tower-lsp#184](https://github.com/ebkalderon/tower-lsp/pull/184)). As a nice consequence, we also reduce our dependency on `tokio` slightly, and we can remove `Send + 'static` trait bounds on the `I, O` in `Server<I, O>`. These improvements are available in Crates.io with release [v0.11.0](https://github.com/ebkalderon/tower-lsp/releases/tag/v0.11.0).

**Comment by darinmorrison** [comment]
I don't intend to pursue this for now so closing.

**Comment by darinmorrison** [comment]
This is implemented now.
