### ISSUE TITLE
Fix document symbols bug in func.wast

### ISSUE THREAD

**Issue by darinmorrison** [wasm-lsp/wasm-language-server#38]
The computed document symbols for `func.wast` uses an incorrect name for the entry for the `$complex` definition:

```wasm
(func $complex
  (param i32 f32) (param $x i64) (param) (param i32)
  (result) (result i32) (result)
  (local f32) (local $y i32) (local i64 i32) (local) (local f64 i32)
  (unreachable) (unreachable)
)
```

The entry in document symbols should be named `$complex` but instead is named `func`.

**Comment by darinmorrison** [comment]
It appears that if I remove the last line in the `func` body, e.g., `(unreachable) (unreachable)`, then the name for the entry is computed correctly. This is probably a bug in the parser.

**Comment by darinmorrison** [comment]
After some experimentation it turns out that this is due to a bug/design-issue in tree-sitter. See https://github.com/tree-sitter/tree-sitter/issues/511. I've solved it by reducing the number of fields used in the grammar.

**Comment by maxbrunsfeld** [comment]
I finally got around to [fixing](https://github.com/tree-sitter/tree-sitter/pull/943) that Tree-sitter bug. Sorry for the poor experience there.
