### ISSUE TITLE
Migrate to tower-lsp v0.12.0

### ISSUE THREAD

**Issue by darinmorrison** [wasm-lsp/wasm-language-server#47]
See version [v0.12.0](https://github.com/ebkalderon/tower-lsp/releases/tag/v0.12.0).

I tried briefly to update the code base to use the new `tower-lsp` version. The server seems to work okay but all the tests are broken now (after fixing the type errors from the API). Not sure why.

Think I will hold off on updating this until the work on WASM feature proposals is complete.

**Comment by ebkalderon** [comment]
Anything I can help with on my end, @darinmorrison? I'd like to verify that the JSON-RPC refactoring done in 0.12.0 hasn't accidentally broken something downstream.

**Comment by darinmorrison** [comment]
Hmm, good question! Later today I will upload a branch with the server working but with the failing tests I mentioned.

At first I thought the issue might be related to some difference in serialization/deserialization logic that needs to be accounted for (I did have to make a couple small changes for that already). However, it seemed even the tests for server initialization were failing with some message about `invalid method`, so I'm not so sure now. Didn't have a chance to investigate further yet.

One thing I was hoping might give some insight is I was planning to look through the library tests in `tower-lsp` to see how they have been updated for the new API. Could just be something stupid I was missing.

The fact that the server still seems to work is promising though 😄

**Comment by ebkalderon** [comment]
Thanks, that's good to know! I'd be happy to take a look whenever you have time to upload a sample, and I can quickly publish a new patch release with fixes, if issues exist.

One thing I did want to mention: [this particular `initialized` notification test case](https://github.com/wasm-lsp/wasm-language-server/blob/f71a07999045328a8c6776dbcaad427b3e7b8ba7/crates/server/tests/lib.rs#L93) is incorrect according to [the LSP spec](https://microsoft.github.io/language-server-protocol/specification#initialized); there should be a `"params":{}` present. `jsonrpc-core` seems to be pretty permissive about this, but I had a test case in `tower-lsp` fail under the new plain `serde` deserializer for probably similar reasons (details in [this commit message](https://github.com/ebkalderon/tower-lsp/commit/07c0e6c5ee097c4e400fec982a2cf5030126d44c)).

Not sure about the other tests, but `invalid method` could be indicative of a typo on my end in [one of these attributes](https://github.com/ebkalderon/tower-lsp/blob/master/src/lib.rs#L113), or it could be related to breaking changes on the `lsp-types` side.

Whatever the issues are, I'm happy to help troubleshoot and fix!

**Comment by darinmorrison** [comment]
@ebkalderon I've created a branch for updating the server to `tower-lsp` version `0.12.0` here: https://github.com/wasm-lsp/wasm-language-server/tree/tower-lsp-update.

After some investigation it appears that there is indeed some problem with serialization/deserialization but I don't really understand what exactly is going wrong.

If you look at the function `call` [here](https://github.com/wasm-lsp/wasm-language-server/blob/2dec78823a7f5f7343b4bf63ca3cde7d47f8d6f1/crates/server/src/lib.rs#L65-L72), you can see where I log the `request` value twice.

The first time it is a `serde_json::Value`. The second time it should be converted to `Incoming::Request`. But from looking at console logs, it appears it is always returning as an `Incoming::Invalid`:

Here is the output from running the `initialize test`. Note the ("before serde") and ("after serde"):

```
---- lsp::initialize stdout ----
before serde: Object({
    "id": Number(
        1,
    ),
    "jsonrpc": String(
        "2.0",
    ),
    "method": String(
        "initialize",
    ),
    "params": Object({
        "capabilities": Object({}),
    }),
})
 after serde: Invalid {
    id: Some(
        Number(
            1,
        ),
    ),
    method: Some(
        "initialize",
    ),
}
thread 'lsp::initialize' panicked at 'assertion failed: `(left == right)`
  left: `Ok(Some(Object({"error": Object({"code": Number(-32601), "message": String("Method not found")}), "id": Number(1), "jsonrpc": String("2.0")})))`,
 right: `Ok(Some(Object({"id": Number(1), "jsonrpc": String("2.0"), "result": Object({"capabilities": Object({"documentSymbolProvider": Bool(true), "textDocumentSync": Object({"change": Number(1), "openClose": Bool(true)})})})})))`', crates/server/tests/lib.rs:85:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I was able to fix the `initialize` test by changing the code [here](https://github.com/wasm-lsp/wasm-language-server/blob/2dec78823a7f5f7343b4bf63ca3cde7d47f8d6f1/crates/server/tests/lib.rs#L64-L71) from the following:

```rust
        let request = &json!({
            "jsonrpc": "2.0",
            "method": "initialize",
            "params": {
                "capabilities":{},
            },
            "id": 1,
        });
```

to this:

```rust
        let request = r#"{
            "jsonrpc": "2.0",
            "method": "initialize",
            "params": {
                "capabilities":{}
            },
            "id": 1
        }"#;
```

and then also accounting for the fact that I needed to use `serde_json::from_str`, etc., in a few places.

However, I tried converting the rest of the code to use raw strings instead of `json!` but the other tests were still failing and I haven't dug any deeper yet.

If you have ideas on what is going wrong here and how to easily fix it, that would be awesome.

**Comment by ebkalderon** [comment]
Good news! I've reproduced the issue with plain `serde` and identified a bug in the [`Deserialize` implementation for the `"jsonrpc"` field](https://github.com/ebkalderon/tower-lsp/blob/4334e6ea169c7653dd1d523958d7444b4378bbcb/src/jsonrpc.rs#L230). It turns out that unlike `serde_json::from_str()`, `from_value()` always passes an owned `String` to the `Deserialize` implementation instead of a `str`, causing the deserialization to fail.

I'm able to get the `wasm-language-server` tests to pass by changing the linked line in the `tower-lsp` source to:

```rust
match Cow::<'de, str>::deserialize(deserializer)?.as_ref() {
```

I can push out a fix for this right away. I apologize for the breakage!

**Comment by ebkalderon** [comment]
Upstream fix is ready in https://github.com/ebkalderon/tower-lsp/pull/209!

**Comment by darinmorrison** [comment]
@ebkalderon Awesome, thanks for looking into that and implementing a fix so quickly!

**Comment by ebkalderon** [comment]
Release [0.12.1](https://github.com/ebkalderon/tower-lsp/releases/tag/v0.12.1) is now out on crates.io! This should fix the deserialization issue you've been experiencing. Granted, the `exit` integration test still won't pass for other reasons and needs to be tweaked as described in https://github.com/wasm-lsp/wasm-language-server/issues/47#issuecomment-671221355, but apart from that, I believe all outstanding issues would be fixed with this release.

**Comment by darinmorrison** [comment]
Just updated to the new release and I was able to get all the tests working (including the exit test using your suggestion regarding `"params": {}`). Thanks for the help!

**Comment by ebkalderon** [comment]
Fantastic! Glad it worked for you, @darinmorrison. Sorry about the breakage. Thanks for posting the WIP code to a branch; having that on hand was invaluable for diagnosis!
